version: '3.4'

services:
    api:
        depends_on:
            - server_db
        image: ${DOCKER_REGISTRY-}api
        build:
            context: .
            dockerfile: API/Dockerfile
        ports:
            - "6003:80"
    server_db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: always
        environment:
            SA_PASSWORD: "Jf9Ls2pRqX"
            ACCEPT_EULA: "Y"
        ports:
            - "4500:1433"

       
